### ISSUE TITLE
Bad use of U35

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/itema3converter#12]
normally, in Performances, U35 should be not used (use U31 instead)

**Comment by pierrechoffe** [comment]
Absolutely. As a reminder, 
1. CRM & FRBRoo have a convention that properties linked to Event derived classes use the past tense (had function), which is not the case with U35 (foresees function)
2. [this table](https://docs.google.com/spreadsheets/d/1RNhHnp4fWEhG8G4acx8FPi-nu9fUWNhc8JNf3SQwUFE/edit#gid=1401336326) has all the info needed

**Comment by rtroncy** [comment]
@pierrechoffe sure, but what's the problem with the current present tense of the labels of the properties U35, U36 and U37? This is the same case than the property U2 for example

**Comment by pierrechoffe** [comment]
They are not linked with Event derived classes but with Design or Procedure classes, so their name should be in present tense (foresees xxx).

**Comment by rtroncy** [comment]
Right. I thought that [your reminder](https://github.com/DOREMUS-ANR/itema3converter/issues/12#issuecomment-394063849) aimed to flag such an inconsistency in one of our property label, and in particular, for U35, but this is not the case.

**Comment by pasqLisena** [comment]
nothing to fix here.
(but [here](https://github.com/DOREMUS-ANR/marc2rdf/issues/80) yes)
