### ISSUE TITLE
Movements management in titles

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/itema3converter#18]
Reference table: https://docs.google.com/spreadsheets/d/11gVJxWk3NF95ZU3qXoFj1YXQ7ykPEIsTN3BTJWj0Uv0

----
### 1. Autonomous work

Si Title ITEMA3 n’a pas `:` c’est qu’il s’agit d’une œuvre autonome.

Il faut donc faire :
```
F22 P102 has Title E35 Title = Title ITEMA3 en supprimant ce qui est dans la colonne M (alternate title)
F22 U68 has variant Title E35 = colonne M (alternate title)
```

Example:
- Ligne 3 : Concerto n°5 en Fa Majeur op 103 "L'Egyptien"
- Ligne 5 : 
   - Title = Sérénade andalouse
   - Variant Title = Serenata andaluza

### 2. Part of a work
Si Title ITEMA3 a `:`, c’est qu’il s’agit de la description d’une partie d’oeuvre.

**OPTION 1.**  Tu crées simplement une œuvre « partie » en supprimant « (extrait) » et en supprimant ce qui est dans la colonne M (alternate title), sans faire de lien avec une notice « mère »

Ex : ligne 8 : 
F14 U95 has hierarchical level M62 Hierachical Level : partie
F22 P102 has Title E35 Title : 8 Klavierstücke op 76 (extrait) : Capriccio en si mineur op 76

**OPTION 2.** Si tu peux, tu crées : 
- une œuvre « mère » avec pour titre tout ce qui est avant les : mais en supprimant « (extrait) » et en supprimant ce qui est dans la colonne M (alternate Title)
- une œuvre « partie » avec pour titre tout ce qui est après les : en supprimant « (extrait) » et en supprimant ce qui est dans la colonne M (alternate Title) sauf ce qui commence par Acte ou acte ou Sc

Example:
- Ligne 8 : 
    - F22 (œuvre mère) P102 has Title E35 : 8 Klavierstücke op 76
    - F14 (œuvre mère) P148 has component F22 œuvre « partie »
    - F22 (œuvre partie) P102 has Title E35 : capriccio en si mineur op 76 n°2

Pour ces parties, il y a peut-être aussi le « genre » `EXTRAIT (MUSIQUE)`  (voir #15). Il faudrait appliquer les règles ci-dessus pour les titres.

-- issue by _Martine_

**Comment by pasqLisena** [comment]
> 1. Autonomous work

This is correctly implemented

> 2. Part of a work

For the moment, I split the title around `:`, keeping only the 1st part.
The full title is preserved in the performed expression.

So the result is:
```turtle
<http://data.doremus.org/expression/0c50028f-7a74-3515-9717-5c79711a99f9>
        a mus:M43_Performed_Expression ;
        rdfs:label "Sonate n°6 en Ré Majeur K 284 \"Durnitz\" : 3ème mouvement, Variation n°11" ;
        mus:U54_is_performed_expression_of
                <http://data.doremus.org/expression/193e753c-4251-3e3e-badb-16e56d7ce117> .


<http://data.doremus.org/expression/193e753c-4251-3e3e-badb-16e56d7ce117>
        a                         efrbroo:F22_Self-Contained_Expression ;
        rdfs:label                "Sonate n°6 en Ré Majeur K 284 \"Durnitz\""  .
```

I think this can be an acceptable tradeout between the request and the easiness of implementation, reducing the number of F22 that have to be interlinked.

**Comment by pasqLisena** [comment]
`P148 has component` links normally 2 works (F14)

**Comment by pasqLisena** [comment]
Implementation complete: _8 Klavierstücke op 76 (extrait) : Capriccio en si mineur op 76 n°2_

```turtle
# Child
<http://data.doremus.org/expression/de4c778b-ccd5-3d7f-8a9c-e26c73d3864e>
        a                           efrbroo:F22_Self-Contained_Expression ;
        rdfs:label                  "Capriccio en si mineur op 76 n°2" .

<http://data.doremus.org/work/b83e5db5-e021-3588-9c5d-5b29801bd06b>
        a                          efrbroo:F14_Individual_Work ;
        efrbroo:R9_is_realised_in  <http://data.doremus.org/expression/de4c778b-ccd5-3d7f-8a9c-e26c73d3864e> .

<http://data.doremus.org/work/4352ed93-fd74-3bee-b671-b8353f852ec9>
        a                          efrbroo:F14_Individual_Work ;
        ecrm:P148_has_component    <http://data.doremus.org/work/b83e5db5-e021-3588-9c5d-5b29801bd06b> ;
        efrbroo:R9_is_realised_in  <http://data.doremus.org/expression/269566ae-cb11-304f-9ba9-93324d5542f6> .

<http://data.doremus.org/expression/269566ae-cb11-304f-9ba9-93324d5542f6>
        a                           efrbroo:F22_Self-Contained_Expression ;
        rdfs:label                  "8 Klavierstücke op 76" .
```

**Comment by pierrechoffe** [comment]
````
P148 has component links normally 2 works (F14)
````
Better use R5 has component, they link 2 expressions (F22)

**Comment by rtroncy** [comment]
Good point: to be discussed if we want to use only P148 between the 2 F14, or R5 between the 2 F22, or both

**Comment by pasqLisena** [comment]
We are currently using `P148`, but I agree in using `R5`

**Comment by pasqLisena** [comment]
in doubt, I use both
