### ISSUE TITLE
Catalogue statement without space

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/itema3converter#19]
Je rectifie ce que j'ai dit lors de notre AG concernant l'extraction de numéros de catalogues à partir des titres de itema3: cela a été fait correctement pour un certain nombre de ressources (il y en a simplement beaucoup qui n'ont pas de numéros de catalogue du tout). Par contre, il existe toujours un nombre d'instances pour lesquelles il semble que cela n'a pas été fait, voici un exemple de la nouvelle livraison itema3:

```turtle
<http://data.doremus.org/expression/c4a77640-84ba-31e7-abf0-89e52e317480>
       a                           efrbroo:F22_Self-Contained_Expression ;
       rdfs:comment                "pour voix et piano, transcription non identifi?e pour septuor ? cordes"@fr ;
       rdfs:label                  "5 Lieder op 41 TrV195" ;
       mus:U12_has_genre           <http://data.doremus.org/vocabulary/itema3/genre/musdoc/51> , <http://data.doremus.org/vocabulary/itema3/genre/musdoc/116> ;
       mus:U17_has_opus_statement  <http://data.doremus.org/expression/c4a77640-84ba-31e7-abf0-89e52e317480/opus/41> ;
       mus:U19_has_style           [ a           mus:M19_Style ;
                                     rdfs:label  "septuor"
                                   ] ;
       mus:U19_has_style           [ a           mus:M19_Style ;
                                     rdfs:label  "musique de chambre"
                                   ] ;
       ecrm:P102_has_title         "5 Lieder op 41 TrV195" ;
       ecrm:P3_has_note            "pour voix et piano, transcription non identifi?e pour septuor ? cordes"@fr ;
       dcterms:identifier          "m20069639" .
```

Le numéro de catalogue est TrV195 (identifié chez la BnF).

-- issue by @kgtodorov

**Comment by pasqLisena** [comment]
The problem here is the missing of the space (`TrV 195` or `TrV.195` would have recognised correctly). I try to see if including these cases do not have bad effects on the rest.

Have you other examples **not** involving the missing space?
Just to be sure that we fully fix the bug.

**Comment by pierrechoffe** [comment]
as an aside, if I'm not wrong, the following

ecrm:P3_has_note            "pour voix et piano, transcription non
identifi?e pour septuor ? cordes"@fr

should use property u67_has_subtitle (or u72_has_title_note ?), not
p3_has_note

plus, what do we do with unrecognized special characters (é and à
transformed into ?)


2018-07-16 11:55 GMT+02:00 Pasquale Lisena <notifications@github.com>:

**Comment by rtroncy** [comment]
> plus, what do we do with unrecognized special characters (é and à transformed into ?)

Those characters are well handled in the data. Konstantin made a copy paste from a UI that doesn't display well. @pierrechoffe Don't trust UI, trust the data :-)

**Comment by rtroncy** [comment]
Regarding the choice of the most appropriate property, this is a decision of Martine. ecrm:P3 is indeed generic. I'm not sure how much we make use already of mus:U72 or mus:U67. @pasqLisena Can you ask Martine what the mapping should be? Or you may have also an opinion of what should be used

**Comment by pasqLisena** [comment]
That text is in the `OMU_DESCRIPTION` field in the source file (that can potentially contain other kinds of comment).

The `ecrm:P3` property is the only one which (even if generic) fits all the possible contents.

**Comment by rtroncy** [comment]
@pierrechoffe When we will load new dumps in the triple store, than SPARQL will be your friend to get counts and usage information.

**Comment by pasqLisena** [comment]
Other examples:
- http://data.doremus.org/expression/584f6a27-90c1-3424-8cb8-337a3c8fcceb
- http://data.doremus.org/expression/21d3dba8-e3f9-3ba4-a12d-c21b18fb719e
- http://data.doremus.org/expression/ddff114d-f92e-3579-a78c-e59d2cc03fc3

**Comment by pasqLisena** [comment]
Last commit solve the 3 last examples (update of the vocabularies)
