### ISSUE TITLE
Not parse empty sampling rate

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/itema3converter#6]
If there is no sampling rate, do not add the property.
http://data.doremus.org/rate/

**Comment by rtroncy** [comment]
http://data.doremus.org/rate/ is an instance of ```ecrm:E54_Dimension```? When is this instance created?

**Comment by pasqLisena** [comment]
We use Dimension for specifying the sampling rate. It is created with the Recording.
http://data.doremus.org/recording/2ec53e9c-eab8-3451-8312-cd6980a66ec4.

This is instead a correct example (48kHz):
http://data.doremus.org/rate/48

**Comment by rtroncy** [comment]
This is what I saw. Do we really need this long path F26 -> P43 -> doremus/rate/xx ->P2 -> dbpedia:Sampling_rate ? Don't we want to re-use an existing property rather than creating instances of P43?

http://lov.okfn.org/dataset/lov/terms?q=sampling+rate provides some possibilities

**Comment by pasqLisena** [comment]
So, looking around, the best candidates are:
- http://dbpedia.org/ontology/frequency 
- https://www.w3.org/ns/ma-ont#samplingRate ([ttl](https://www.w3.org/ns/ma-ont.ttl)) (+1 from my side)

(all in Hz, multiply by 1000 the kHz)

**Comment by rtroncy** [comment]
I would favor http://dbpedia.org/ontology/frequency ... which is more used.

```ma-ont:samplingRate``` is defined as "an audio sampling rate where the units are defined to be samples/second."
